baseURL: /
languageCode: en-us
title: CODD-K Articles
contentdir: content
layoutdir: layouts
publishdir: public
builddrafts: true
canonifyurls: true
theme: codd-k
taxonomies:
  category: categories
  group: groups
  series: series
  tag: tags
params:
  subtitle: Articles by CODD-K
  copyrightHolder: CODD-K
  showPoweredBy: false
menu:
  nav:
    - name: Home
      pre: '<i class=''fa fa-home fa-lg''></i> '
      weight: -110
      identifier: home
      url: /
    - name: Posts
      pre: '<i class=''fa fa-book fa-lg''></i> '
      weight: -100
      identifier: posts
      url: /post
    - name: Categories
      pre: '<i class=''fa fa-tags fa-lg''></i> '
      weight: -90
      identifier: categories
      url: /categories
  footer:
    - name: ''
      pre: '<i class=''fa fa-github fa-2x''></i> '
      weight: -100
      identifier: github
      url: 'https://github.com/shawnohare/hugo-tufte'
    - name: ''
      pre: '<i class=''fa fa-twitter fa-2x''></i> '
      weight: -90
      identifier: twitter
      url: 'https://twitter.com'
